const roles=['Server Hardware • Break/Fix • Remote Hands','Network Engineering • Arista • Cisco','Fiber Optics • SMF/MMF • OTDR','Rack & Stack • Power • Data Center Operations'];
let r=0,c=0,d=false,t=document.querySelector('#typed');
function type(){if(!t)return;let s=roles[r];t.textContent=s.slice(0,c);if(!d&&c<s.length){c++;setTimeout(type,48)}else if(!d){d=true;setTimeout(type,1350)}else if(c>0){c--;setTimeout(type,24)}else{d=false;r=(r+1)%roles.length;setTimeout(type,250)}} setTimeout(type,800);
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
let done=false;const m=document.querySelector('.metrics');if(m)new IntersectionObserver(es=>{if(es[0].isIntersecting&&!done){done=true;document.querySelectorAll('[data-n]').forEach(e=>{let n=+e.dataset.n,s=performance.now();function a(x){let p=Math.min((x-s)/900,1);e.textContent=Math.floor(n*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(a)}requestAnimationFrame(a)})}},{threshold:.25}).observe(m);
const progress=document.querySelector('#progress');addEventListener('scroll',()=>{if(progress)progress.style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%';document.querySelector('header')?.classList.toggle('scrolled',scrollY>28)},{passive:true});
document.querySelector('#year').textContent=new Date().getFullYear();
// Smooth one-page navigation
const links=[...document.querySelectorAll('.navRoute')];links.forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id?.startsWith('#')){e.preventDefault();document.querySelector(id)?.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',id)}}));
const sections=['home','about','experience','work','skills'].map(id=>document.getElementById(id)).filter(Boolean);const navObs=new IntersectionObserver(es=>{const visible=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+visible.target.id));},{rootMargin:'-20% 0px -65% 0px',threshold:[0,.1,.3]});sections.forEach(s=>navObs.observe(s));
